import { CategoryItem, PopularCategoryItem } from "@/types/categories";

export const ALL_CATEGORIES: CategoryItem[] = [
  {
    id: "sports",
    name: "Sports",
    eventsCount: 124,
    description: "From local games to major tournaments, catch the action and support your team.",
    iconName: "Trophy",
    iconBg: "bg-blue-600 shadow-[0_0_16px_rgba(37,99,235,0.45)]",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop",
    slug: "sports",
    href: "/events/sports",
    isPopular: true,
    tags: ["sports", "football", "basketball", "tennis", "running", "gym", "martial arts", "matches"],
  },
  {
    id: "concerts",
    name: "Concerts",
    eventsCount: 98,
    description: "Live music, big artists, and unforgettable performances.",
    iconName: "Music",
    iconBg: "bg-purple-600 shadow-[0_0_16px_rgba(147,51,234,0.45)]",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop",
    slug: "concerts",
    href: "/events/concerts",
    isPopular: true,
    tags: ["concerts", "music", "live", "pop", "rock", "hip-hop", "bands", "tours"],
  },
  {
    id: "theater",
    name: "Theater",
    eventsCount: 62,
    description: "Classic plays, modern shows, and captivating performances.",
    iconName: "Drama",
    iconBg: "bg-amber-600 shadow-[0_0_16px_rgba(217,119,6,0.45)]",
    image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?q=80&w=800&auto=format&fit=crop",
    slug: "theater",
    href: "/events/theater",
    isPopular: true,
    tags: ["theater", "drama", "plays", "broadway", "musical", "opera", "ballet"],
  },
  {
    id: "festivals",
    name: "Festivals",
    eventsCount: 76,
    description: "Celebrate culture, music, food and unforgettable moments.",
    iconName: "Sparkles",
    iconBg: "bg-emerald-600 shadow-[0_0_16px_rgba(16,185,129,0.45)]",
    image: "https://images.unsplash.com/photo-1492684223066-81342ee5ff30?q=80&w=800&auto=format&fit=crop",
    slug: "festivals",
    href: "/events/festivals",
    isPopular: true,
    tags: ["festivals", "fireworks", "food", "music festival", "celebration", "party"],
  },
  {
    id: "conferences",
    name: "Conferences",
    eventsCount: 45,
    description: "Learn, connect and grow with industry leaders and experts.",
    iconName: "Users",
    iconBg: "bg-cyan-600 shadow-[0_0_16px_rgba(8,145,178,0.45)]",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&auto=format&fit=crop",
    slug: "conferences",
    href: "/events/conferences",
    isPopular: false,
    tags: ["conferences", "tech", "summit", "keynote", "networking", "seminar"],
  },
  {
    id: "workshops",
    name: "Workshops",
    eventsCount: 38,
    description: "Build new skills and explore your creativity.",
    iconName: "Wrench",
    iconBg: "bg-indigo-600 shadow-[0_0_16px_rgba(79,70,229,0.45)]",
    image: "https://images.unsplash.com/photo-1513364776144-60967b0f800f?q=80&w=800&auto=format&fit=crop",
    slug: "workshops",
    href: "/events/workshops",
    isPopular: false,
    tags: ["workshops", "skills", "coding", "design", "art", "hands-on", "masterclass"],
  },
  {
    id: "exhibitions",
    name: "Exhibitions",
    eventsCount: 29,
    description: "Discover art, innovation and inspiring ideas.",
    iconName: "Image",
    iconBg: "bg-pink-600 shadow-[0_0_16px_rgba(219,39,119,0.45)]",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=800&auto=format&fit=crop",
    slug: "exhibitions",
    href: "/events/exhibitions",
    isPopular: false,
    tags: ["exhibitions", "art", "museum", "gallery", "exhibit", "expo", "showcase"],
  },
  {
    id: "cultural",
    name: "Cultural",
    eventsCount: 34,
    description: "Immerse in heritage, folkloric traditions, and ancient history.",
    iconName: "Landmark",
    iconBg: "bg-amber-500 shadow-[0_0_16px_rgba(245,158,11,0.45)]",
    image: "https://images.unsplash.com/photo-1539650116574-8efeb43e2750?q=80&w=800&auto=format&fit=crop",
    slug: "cultural",
    href: "/events/cultural",
    isPopular: false,
    tags: ["cultural", "heritage", "monuments", "culture", "traditions", "history"],
  },
  {
    id: "gaming",
    name: "Gaming",
    eventsCount: 42,
    description: "Compete in esports arenas, gaming conventions, and live tournaments.",
    iconName: "Gamepad2",
    iconBg: "bg-violet-600 shadow-[0_0_16px_rgba(124,58,237,0.45)]",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=800&auto=format&fit=crop",
    slug: "gaming",
    href: "/events/gaming",
    isPopular: false,
    tags: ["gaming", "esports", "tournaments", "lan", "video games", "streamers"],
  },
  {
    id: "family",
    name: "Family",
    eventsCount: 31,
    description: "Wholesome entertainment, magical circus shows, and fun for all ages.",
    iconName: "Heart",
    iconBg: "bg-rose-500 shadow-[0_0_16px_rgba(244,63,94,0.45)]",
    image: "https://images.unsplash.com/photo-1513151233558-d860c5398176?q=80&w=800&auto=format&fit=crop",
    slug: "family",
    href: "/events/family",
    isPopular: false,
    tags: ["family", "kids", "fun", "circus", "magic", "carnival", "all ages"],
  },
  {
    id: "business",
    name: "Business",
    eventsCount: 27,
    description: "Connect with investors, founders, and corporate leaders at premier forums.",
    iconName: "Briefcase",
    iconBg: "bg-sky-600 shadow-[0_0_16px_rgba(2,132,199,0.45)]",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?q=80&w=800&auto=format&fit=crop",
    slug: "business",
    href: "/events/business",
    isPopular: false,
    tags: ["business", "corporate", "investor", "startup", "finance", "leadership"],
  },
  {
    id: "other",
    name: "Other",
    eventsCount: 17,
    description: "Unique experiences and special events, all in one place.",
    iconName: "Star",
    iconBg: "bg-slate-600 shadow-[0_0_16px_rgba(71,85,105,0.45)]",
    image: "https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?q=80&w=800&auto=format&fit=crop",
    slug: "other",
    href: "/events/other",
    isPopular: false,
    tags: ["other", "special", "unique", "stargazing", "drone show", "experiences"],
  },
];

export const POPULAR_CATEGORIES: PopularCategoryItem[] = [
  {
    id: "sports",
    name: "Sports",
    eventsCount: 124,
    iconName: "Trophy",
    iconBg: "bg-blue-600",
    href: "/events/sports",
  },
  {
    id: "concerts",
    name: "Concerts",
    eventsCount: 98,
    iconName: "Music",
    iconBg: "bg-purple-600",
    href: "/events/concerts",
  },
  {
    id: "festivals",
    name: "Festivals",
    eventsCount: 76,
    iconName: "Sparkles",
    iconBg: "bg-emerald-600",
    href: "/events/festivals",
  },
  {
    id: "theater",
    name: "Theater",
    eventsCount: 62,
    iconName: "Drama",
    iconBg: "bg-amber-600",
    href: "/events/theater",
  },
];
