import { CategoryEvent, CategoryPillItem } from "@/types/events";

export const SUBCATEGORIES_BY_CATEGORY: Record<string, CategoryPillItem[]> = {
  all: [
    { id: "all", label: "All", iconName: "LayoutGrid", subcategoryId: "all" },
    { id: "concerts", label: "Concerts", iconName: "Music", subcategoryId: "concerts" },
    { id: "festivals", label: "Festivals", iconName: "Sparkles", subcategoryId: "festivals" },
    { id: "conferences", label: "Conferences", iconName: "Users", subcategoryId: "conferences" },
    { id: "workshops", label: "Workshops", iconName: "GraduationCap", subcategoryId: "workshops" },
    { id: "theater", label: "Theater", iconName: "Drama", subcategoryId: "theater" },
    { id: "cultural", label: "Cultural", iconName: "Landmark", subcategoryId: "cultural" },
    { id: "exhibitions", label: "Exhibitions", iconName: "Image", subcategoryId: "exhibitions" },
    { id: "other", label: "Other", iconName: "MoreHorizontal", subcategoryId: "other" },
  ],
  events: [
    { id: "all", label: "All", iconName: "LayoutGrid", subcategoryId: "all" },
    { id: "concerts", label: "Concerts", iconName: "Music", subcategoryId: "concerts" },
    { id: "festivals", label: "Festivals", iconName: "Sparkles", subcategoryId: "festivals" },
    { id: "conferences", label: "Conferences", iconName: "Users", subcategoryId: "conferences" },
    { id: "workshops", label: "Workshops", iconName: "GraduationCap", subcategoryId: "workshops" },
    { id: "theater", label: "Theater", iconName: "Drama", subcategoryId: "theater" },
    { id: "cultural", label: "Cultural", iconName: "Landmark", subcategoryId: "cultural" },
    { id: "exhibitions", label: "Exhibitions", iconName: "Image", subcategoryId: "exhibitions" },
    { id: "other", label: "Other", iconName: "MoreHorizontal", subcategoryId: "other" },
  ],
  sports: [
    { id: "all", label: "All Sports", iconName: "LayoutGrid", subcategoryId: "all" },
    { id: "football", label: "Football", iconName: "CircleDot", subcategoryId: "football" },
    { id: "basketball", label: "Basketball", iconName: "Flame", subcategoryId: "basketball" },
    { id: "tennis", label: "Tennis", iconName: "Activity", subcategoryId: "tennis" },
    { id: "running", label: "Running", iconName: "Footprints", subcategoryId: "running" },
    { id: "gym", label: "Gym & Fitness", iconName: "Dumbbell", subcategoryId: "gym" },
    { id: "martial-arts", label: "Martial Arts", iconName: "Shield", subcategoryId: "martial-arts" },
    { id: "other", label: "Other Sports", iconName: "MoreHorizontal", subcategoryId: "other" },
  ],
  concerts: [
    { id: "all", label: "All Concerts", iconName: "LayoutGrid", subcategoryId: "all" },
    { id: "pop", label: "Pop", iconName: "Music", subcategoryId: "pop" },
    { id: "rock", label: "Rock", iconName: "Radio", subcategoryId: "rock" },
    { id: "hip-hop", label: "Hip-Hop", iconName: "Mic", subcategoryId: "hip-hop" },
    { id: "electronic", label: "Electronic", iconName: "Zap", subcategoryId: "electronic" },
    { id: "classical", label: "Classical", iconName: "Volume2", subcategoryId: "classical" },
    { id: "other", label: "Other Shows", iconName: "MoreHorizontal", subcategoryId: "other" },
  ],
  theater: [
    { id: "all", label: "All Theater", iconName: "LayoutGrid", subcategoryId: "all" },
    { id: "musical", label: "Musical", iconName: "Music", subcategoryId: "musical" },
    { id: "drama", label: "Drama", iconName: "Drama", subcategoryId: "drama" },
    { id: "comedy", label: "Comedy", iconName: "Smile", subcategoryId: "comedy" },
    { id: "opera", label: "Opera", iconName: "Mic", subcategoryId: "opera" },
    { id: "ballet", label: "Ballet", iconName: "Footprints", subcategoryId: "ballet" },
    { id: "other", label: "Other Plays", iconName: "MoreHorizontal", subcategoryId: "other" },
  ],
  festivals: [
    { id: "all", label: "All Festivals", iconName: "LayoutGrid", subcategoryId: "all" },
    { id: "music-festivals", label: "Music Festivals", iconName: "Music", subcategoryId: "music-festivals" },
    { id: "cultural", label: "Cultural", iconName: "Globe", subcategoryId: "cultural" },
    { id: "food-arts", label: "Food & Arts", iconName: "Utensils", subcategoryId: "food-arts" },
    { id: "seasonal", label: "Seasonal", iconName: "Sparkles", subcategoryId: "seasonal" },
    { id: "other", label: "Other Events", iconName: "MoreHorizontal", subcategoryId: "other" },
  ],
};

export const CATEGORY_HERO_CONFIGS: Record<
  string,
  { badge: string; titleFirst: string; titleAccent: string; description: string }
> = {
  all: {
    badge: "Discover & Explore",
    titleFirst: "Unforgettable",
    titleAccent: "Events Await",
    description:
      "From thrilling concerts and cultural festivals to exciting workshops and conferences — find the perfect event for you.",
  },
  events: {
    badge: "Discover & Explore",
    titleFirst: "Unforgettable",
    titleAccent: "Events Await",
    description:
      "From thrilling concerts and cultural festivals to exciting workshops and conferences — find the perfect event for you.",
  },
  sports: {
    badge: "Sports & Competitions",
    titleFirst: "Unforgettable",
    titleAccent: "Sports Await",
    description:
      "From thrilling football clashes to basketball leagues, marathon races, and martial arts championships — experience peak athleticism live.",
  },
  concerts: {
    badge: "Live Music & Tours",
    titleFirst: "Electrifying",
    titleAccent: "Concerts Await",
    description:
      "Experience world-class arena tours, stadium concerts, and unforgettable musical performances from your favorite global artists.",
  },
  theater: {
    badge: "Stage & Drama",
    titleFirst: "Spectacular",
    titleAccent: "Shows Await",
    description:
      "Immerse yourself in legendary theatrical plays, classical ballet, stand-up comedy, and world-renowned Broadway performances.",
  },
  festivals: {
    badge: "Festivals & Celebrations",
    titleFirst: "Vibrant",
    titleAccent: "Festivals Await",
    description:
      "Celebrate life with multi-day music festivals, cultural celebrations, food fiestas, and seasonal gatherings.",
  },
};

export const ALL_CATEGORY_EVENTS: CategoryEvent[] = [
  // =========================================================================
  // THE 6 EXACT CARDS SHOWN IN THE USER'S NEW TICKET-DESIGN SCREENSHOT:
  // =========================================================================
  {
    id: "coldplay-live-cairo",
    title: "Coldplay Live in Cairo",
    category: "concerts",
    subcategory: "concerts",
    subcategoryLabel: "Concert",
    date: "Nov 20, 2025",
    time: "8:00 PM",
    fullDate: "2025-11-20",
    monthShort: "NOV",
    dayNumber: "20",
    year: "2025",
    venue: "Cairo International Stadium",
    city: "Cairo",
    country: "Egypt",
    minPrice: 75,
    maxPrice: 250,
    priceFormatted: "$75 - $250",
    image: "https://images.unsplash.com/photo-1514525253161-7a46d19cd819?q=80&w=800&auto=format&fit=crop",
    slug: "coldplay-live-in-cairo",
    isPopular: true,
  },
  {
    id: "cairo-music-festival-2025",
    title: "Cairo Music Festival 2025",
    category: "festivals",
    subcategory: "festivals",
    subcategoryLabel: "Festival",
    date: "Dec 12, 2025",
    time: "4:00 PM",
    fullDate: "2025-12-12",
    monthShort: "DEC",
    dayNumber: "12",
    year: "2025",
    venue: "New Administrative Capital",
    city: "Cairo",
    country: "Egypt",
    minPrice: 40,
    maxPrice: 120,
    priceFormatted: "$40 - $120",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop",
    slug: "cairo-music-festival-2025",
    isPopular: true,
  },
  {
    id: "egypt-vs-nigeria",
    title: "Egypt vs Nigeria - Friendly Match",
    category: "sports",
    subcategory: "football",
    subcategoryLabel: "Sports",
    date: "Oct 12, 2025",
    time: "6:00 PM",
    fullDate: "2025-10-12",
    monthShort: "NOV",
    dayNumber: "12",
    year: "2025",
    venue: "Cairo International Stadium",
    city: "Cairo",
    country: "Egypt",
    minPrice: 25,
    maxPrice: 150,
    priceFormatted: "$25 - $150",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop",
    slug: "egypt-vs-nigeria-friendly-match",
    isPopular: true,
  },
  {
    id: "the-last-dream",
    title: "The Last Dream",
    category: "theater",
    subcategory: "theater",
    subcategoryLabel: "Theater",
    date: "Nov 15, 2025",
    time: "7:30 PM",
    fullDate: "2025-11-15",
    monthShort: "NOV",
    dayNumber: "15",
    year: "2025",
    venue: "Cairo Opera House",
    city: "Cairo",
    country: "Egypt",
    minPrice: 30,
    maxPrice: 90,
    priceFormatted: "$30 - $90",
    image: "https://images.unsplash.com/photo-1507676184212-d03ab07a01bf?q=80&w=800&auto=format&fit=crop",
    slug: "the-last-dream",
    isPopular: true,
  },
  {
    id: "full-stack-development-workshop",
    title: "Full Stack Development Workshop",
    category: "workshops",
    subcategory: "workshops",
    subcategoryLabel: "Workshop",
    date: "Nov 08, 2025",
    time: "10:00 AM",
    fullDate: "2025-11-08",
    monthShort: "NOV",
    dayNumber: "08",
    year: "2025",
    venue: "Tahrir Academy",
    city: "Cairo",
    country: "Egypt",
    minPrice: 50,
    maxPrice: 200,
    priceFormatted: "$50 - $200",
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?q=80&w=800&auto=format&fit=crop",
    slug: "full-stack-development-workshop",
    isPopular: true,
  },
  {
    id: "ancient-egypt-exhibition",
    title: "Ancient Egypt Exhibition",
    category: "cultural",
    subcategory: "cultural",
    subcategoryLabel: "Cultural",
    date: "Oct 25, 2025",
    time: "9:00 AM",
    fullDate: "2025-10-25",
    monthShort: "OCT",
    dayNumber: "25",
    year: "2025",
    venue: "Grand Egyptian Museum",
    city: "Giza",
    country: "Egypt",
    minPrice: 20,
    maxPrice: 80,
    priceFormatted: "$20 - $80",
    image: "https://images.unsplash.com/photo-1568605117036-5fe5e7bab0b7?q=80&w=800&auto=format&fit=crop",
    slug: "ancient-egypt-exhibition",
    isPopular: true,
  },

  // =========================================================================
  // PAGE 2 & ONWARDS: ADDITIONAL EVENTS
  // =========================================================================
  {
    id: "the-weeknd-after-hours",
    title: "The Weeknd – After Hours World Tour",
    category: "concerts",
    subcategory: "pop",
    subcategoryLabel: "Concert",
    date: "Nov 12, 2025",
    time: "8:00 PM",
    fullDate: "2025-11-12",
    monthShort: "NOV",
    dayNumber: "12",
    year: "2025",
    venue: "Cairo International Stadium",
    city: "Cairo",
    country: "Egypt",
    minPrice: 79,
    maxPrice: 250,
    priceFormatted: "$79 - $250",
    image: "https://images.unsplash.com/photo-1501386761578-eac5c94b800a?q=80&w=800&auto=format&fit=crop",
    slug: "the-weeknd-after-hours",
    isPopular: true,
  },
  {
    id: "zamalek-vs-ahly-basketball",
    title: "Zamalek vs Al Ahly - Basketball League",
    category: "sports",
    subcategory: "basketball",
    subcategoryLabel: "Sports",
    date: "Oct 18, 2025",
    time: "7:00 PM",
    fullDate: "2025-10-18",
    monthShort: "OCT",
    dayNumber: "18",
    year: "2025",
    venue: "Cairo Stadium",
    city: "Cairo",
    country: "Egypt",
    minPrice: 20,
    maxPrice: 100,
    priceFormatted: "$20 - $100",
    image: "https://images.unsplash.com/photo-1546519638-68e109498ffc?q=80&w=800&auto=format&fit=crop",
    slug: "zamalek-vs-al-ahly-basketball-league",
    isPopular: true,
  },
  {
    id: "soundstorm-2025",
    title: "Soundstorm Music Festival 2025",
    category: "festivals",
    subcategory: "festivals",
    subcategoryLabel: "Festival",
    date: "Dec 05, 2025",
    time: "4:00 PM",
    fullDate: "2025-12-05",
    monthShort: "DEC",
    dayNumber: "05",
    year: "2025",
    venue: "Banban",
    city: "Riyadh",
    country: "Saudi Arabia",
    minPrice: 99,
    maxPrice: 400,
    priceFormatted: "$99 - $400",
    image: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?q=80&w=800&auto=format&fit=crop",
    slug: "soundstorm-2025",
    isPopular: true,
  },
  {
    id: "phantom-of-the-opera",
    title: "The Phantom of the Opera",
    category: "theater",
    subcategory: "theater",
    subcategoryLabel: "Theater",
    date: "Nov 18, 2025",
    time: "8:00 PM",
    fullDate: "2025-11-18",
    monthShort: "NOV",
    dayNumber: "18",
    year: "2025",
    venue: "Cairo Opera House",
    city: "Cairo",
    country: "Egypt",
    minPrice: 45,
    maxPrice: 160,
    priceFormatted: "$45 - $160",
    image: "https://images.unsplash.com/photo-1460723237483-7a6dc9d0b212?q=80&w=800&auto=format&fit=crop",
    slug: "the-phantom-of-the-opera",
    isPopular: true,
  },
  {
    id: "cairo-open-tennis",
    title: "Cairo Open - Tennis Tournament",
    category: "sports",
    subcategory: "tennis",
    subcategoryLabel: "Sports",
    date: "Oct 25, 2025",
    time: "4:00 PM",
    fullDate: "2025-10-25",
    monthShort: "OCT",
    dayNumber: "25",
    year: "2025",
    venue: "Cairo Tennis Club",
    city: "Cairo",
    country: "Egypt",
    minPrice: 15,
    maxPrice: 80,
    priceFormatted: "$15 - $80",
    image: "https://images.unsplash.com/photo-1622279457486-62dcc4a431d6?q=80&w=800&auto=format&fit=crop",
    slug: "cairo-open-tennis-tournament",
    isPopular: false,
  },
  {
    id: "real-madrid-vs-barcelona",
    title: "Real Madrid vs Barcelona - El Clásico",
    category: "sports",
    subcategory: "football",
    subcategoryLabel: "Sports",
    date: "Oct 26, 2025",
    time: "9:00 PM",
    fullDate: "2025-10-26",
    monthShort: "OCT",
    dayNumber: "26",
    year: "2025",
    venue: "Santiago Bernabéu",
    city: "Madrid",
    country: "Spain",
    minPrice: 90,
    maxPrice: 350,
    priceFormatted: "$90 - $350",
    image: "https://images.unsplash.com/photo-1574629810360-7efbbe195018?q=80&w=800&auto=format&fit=crop",
    slug: "real-madrid-vs-barcelona",
    isPopular: true,
  },
  {
    id: "cairo-marathon-2025",
    title: "Cairo Marathon 2025",
    category: "sports",
    subcategory: "running",
    subcategoryLabel: "Sports",
    date: "Nov 02, 2025",
    time: "6:30 AM",
    fullDate: "2025-11-02",
    monthShort: "NOV",
    dayNumber: "02",
    year: "2025",
    venue: "New Cairo",
    city: "Cairo",
    country: "Egypt",
    minPrice: 10,
    maxPrice: 60,
    priceFormatted: "$10 - $60",
    image: "https://images.unsplash.com/photo-1552674605-db6ffd4facb5?q=80&w=800&auto=format&fit=crop",
    slug: "cairo-marathon-2025",
    isPopular: true,
  },
  {
    id: "ufc-fight-night",
    title: "UFC Championship Fight Night",
    category: "sports",
    subcategory: "martial-arts",
    subcategoryLabel: "Sports",
    date: "Dec 02, 2025",
    time: "10:00 PM",
    fullDate: "2025-12-02",
    monthShort: "DEC",
    dayNumber: "02",
    year: "2025",
    venue: "Etihad Arena",
    city: "Abu Dhabi",
    country: "UAE",
    minPrice: 85,
    maxPrice: 320,
    priceFormatted: "$85 - $320",
    image: "https://images.unsplash.com/photo-1549719386-74dfcbf7dbed?q=80&w=800&auto=format&fit=crop",
    slug: "ufc-fight-night-championship",
    isPopular: true,
  },
];

export const LOCATION_OPTIONS = [
  { value: "all", label: "All Locations" },
  { value: "cairo", label: "Cairo, Egypt" },
  { value: "giza", label: "Giza, Egypt" },
  { value: "alexandria", label: "Alexandria, Egypt" },
  { value: "hurghada", label: "Hurghada, Egypt" },
  { value: "riyadh", label: "Riyadh, Saudi Arabia" },
  { value: "madrid", label: "Madrid, Spain" },
  { value: "dubai", label: "Dubai, UAE" },
];
